// 根布局组件：定义整个应用的基础 HTML 结构和全局配置（Next.js 13+ 推荐使用）

// 导入全局样式文件（包含项目通用样式、主题变量等）
import "./globals.css";

// 定义页面元数据（用于 SEO 和浏览器标签页显示）
// 注：Next.js 13+ 中 metadata 会自动注入到 <head> 标签中
export const metadata = {
  title: "Create Next App", // 页面标题（显示在浏览器标签页）
  description: "Generated by create next app", // 页面描述（影响搜索引擎结果）
};

// 根布局组件（必须默认导出，包裹整个应用的内容）
// 参数：children（子组件，即 pages 或 app 目录下的页面内容）
export default function RootLayout({ children }) {
  return (
    // 定义 HTML 文档根标签（lang="en" 设置文档语言为英语）
    <html lang="en">
      {/* 定义页面主体标签，应用全局样式类 */}
      <body
        className={`antialiased`} // Tailwind 实用类：优化字体抗锯齿（使文字更清晰）
      >
        {children} {/* 渲染子组件（即具体页面内容，如 /github-stats 页面） */}
      </body>
    </html>
  );
}